"""AIRCOORD: baseline and centralized MPC comparison.

Run: python aircoord.py --agents 4 --seed 7 --delay 0 --gif
Install: python -m pip install numpy scipy matplotlib pillow

Centralized MPC supports current, stale or compensated reports via --state-source.
Slack and fallback are reported explicitly; this is not a safety guarantee.
Each controller/seed has its own results directory. No RL is included.
"""
from __future__ import annotations
from scipy.optimize import minimize
import argparse
import csv
import json
import time
from dataclasses import asdict, dataclass
from pathlib import Path

import numpy as np


@dataclass(frozen=True)
class Config:
    n: int = 4
    dt: float = 0.1
    duration: float = 60.0
    radius: float = 150.0
    cruise_speed: float = 10.0
    max_speed: float = 15.0
    max_accel: float = 2.0
    max_turn_rate: float = np.deg2rad(30)
    separation: float = 20.0
    goal_radius: float = 5.0
    delay_s: float = 0.0
    jitter: float = 5.0
    accel_noise_std: float = 0.0  # m/s^2, iid per vehicle and dt; plant only

    def __post_init__(self):
        if not isinstance(self.n, int) or not 2 <= self.n <= 32:
            raise ValueError("n must be an integer in [2, 32]")
        for name, value in asdict(self).items():
            if not np.isfinite(value):
                raise ValueError(f"{name} must be finite")
            if name in ("delay_s", "jitter", "accel_noise_std"):
                if value < 0:
                    raise ValueError(f"{name} must be nonnegative")
            elif value <= 0:
                raise ValueError(f"{name} must be positive")
        if self.cruise_speed > self.max_speed:
            raise ValueError("cruise_speed exceeds max_speed")
        if not np.isclose(self.duration / self.dt, round(self.duration / self.dt)):
            raise ValueError("duration must be an integer multiple of dt")
        if not np.isclose(self.delay_s / self.dt, round(self.delay_s / self.dt)):
            raise ValueError("delay_s must be an integer multiple of dt")


def wrap(angle):
    return (angle + np.pi) % (2 * np.pi) - np.pi


def swept_distances(before, after):
    """Exact closest pair distances for the simulator's linear step segments."""
    i, j = np.triu_indices(len(before), 1)
    r = before[i] - before[j]
    dr = (after[i] - before[i]) - (after[j] - before[j])
    denominator = np.sum(dr * dr, axis=1)
    fraction = np.clip(
        -np.sum(r * dr, axis=1) / np.maximum(denominator, 1e-15), 0, 1
    )
    return i, j, np.linalg.norm(r + fraction[:, None] * dr, axis=1)


class TrafficEnv:
    """Custom research API; not yet a Gymnasium/PettingZoo environment.

    State rows: [x_m, y_m, speed_mps, heading_rad].
    Action rows: [longitudinal_accel_mps2, heading_rate_radps].
    Policies receive observe() only. True state belongs to physics/evaluation.
    Arrived agents leave the airspace at the end of their arrival step.
    """

    def __init__(self, config=Config()):
        self.c = config

    def reset(self, seed=0):
        rng = np.random.default_rng(seed)
        # Separate stream: changing noise does not change initial positions.
        # Pre-generated by (time step, vehicle ID), independent of controller,
        # active masks, solver calls and episode termination.
        noise_rng = np.random.default_rng(np.random.SeedSequence([seed, 92831]))
        self.accel_disturbance = self.c.accel_noise_std * noise_rng.standard_normal(
            (int(round(self.c.duration / self.c.dt)), self.c.n))
        angle = np.arange(self.c.n) * 2 * np.pi / self.c.n
        nominal = self.c.radius * np.column_stack((np.cos(angle), np.sin(angle)))
        pos = nominal + rng.uniform(-self.c.jitter, self.c.jitter, nominal.shape)
        self.goals = -nominal
        delta = self.goals - pos
        self.initial_distance = np.linalg.norm(delta, axis=1)
        self.state = np.column_stack((pos, np.full(self.c.n, self.c.cruise_speed),
                                      np.arctan2(delta[:, 1], delta[:, 0])))
        self.active = np.ones(self.c.n, dtype=bool)
        self.arrival = np.full(self.c.n, np.nan)
        self.path_length = np.zeros(self.c.n)
        self.k = 0
        self.history = [self.state.copy()]
        self.active_history = [self.active.copy()]
        self.actions = []
        self.min_history = []
        self.violating_pairs = set()
        self.violation_steps = 0
        self.minimum = float("inf")
        self.seed = seed
        return self.observe()

    def observe(self):
        lag = int(round(self.c.delay_s / self.c.dt))
        old_k = max(0, self.k - lag)
        old = self.history[old_k]
        own = self.state.copy()
        relative = old[None, :, :2] - own[:, None, :2]
        old_velocity = old[:, 2, None] * np.column_stack(
            (np.cos(old[:, 3]), np.sin(old[:, 3])))
        velocity = np.broadcast_to(old_velocity, (self.c.n, self.c.n, 2)).copy()
        mask = np.broadcast_to(self.active_history[old_k], (self.c.n, self.c.n)).copy()
        np.fill_diagonal(mask, False)
        relative[np.arange(self.c.n), np.arange(self.c.n)] = 0
        velocity[np.arange(self.c.n), np.arange(self.c.n)] = 0
        return {"own": own, "goal": self.goals.copy(), "active": self.active.copy(),
                "neighbor_relative_position": relative, "neighbor_velocity": velocity,
                "neighbor_mask": mask, "observation_age_s": (self.k - old_k) * self.c.dt}

    def controller_observation(self, mode='current'):
        """Central report: all dynamic fields share one timestamp.

        Goals are fixed mission information. No current state/active mask is
        exposed in stale mode. Startup history is clamped to reset time.
        """
        if mode not in ('current', 'stale'):
            raise ValueError('state source must be current or stale')
        lag = int(round(self.c.delay_s / self.c.dt)) if mode == 'stale' else 0
        report_k = max(0, self.k - lag)
        return dict(own=self.history[report_k].copy(), goal=self.goals.copy(),
                    active=self.active_history[report_k].copy(),
                    observation_age_s=(self.k - report_k) * self.c.dt)

    def step(self, action):
        if not self.active.any() or self.k >= round(self.c.duration / self.c.dt):
            raise RuntimeError("episode finished; call reset()")
        action = np.asarray(action, dtype=float)
        if action.shape != (self.c.n, 2) or not np.isfinite(action).all():
            raise ValueError(f"action must be finite with shape ({self.c.n}, 2)")
        limits = np.array([self.c.max_accel, self.c.max_turn_rate])
        action = np.clip(action, -limits, limits)
        action[~self.active] = 0
        before = self.state[:, :2].copy()
        moving = self.active.copy()
        # External acceleration is added AFTER command saturation. Thus total
        # acceleration may exceed the actuator bound; speed bounds still apply.
        actual_accel = action[moving, 0] + self.accel_disturbance[self.k, moving]
        self.state[moving, 2] = np.clip(self.state[moving, 2] + actual_accel * self.c.dt,
                                       0, self.c.max_speed)
        self.state[moving, 3] = wrap(self.state[moving, 3] + action[moving, 1] * self.c.dt)
        heading = self.state[:, 3]
        velocity = self.state[:, 2, None] * np.column_stack((np.cos(heading), np.sin(heading)))
        self.state[moving, :2] += velocity[moving] * self.c.dt
        after = self.state[:, :2]
        self.path_length += np.linalg.norm(after - before, axis=1)

        # Check separation throughout each discrete transition, not only at endpoints.
        i, j, distance = swept_distances(before, after)
        valid = moving[i] & moving[j]
        minimum = float(distance[valid].min()) if valid.any() else float("nan")
        if valid.any():
            self.minimum = min(self.minimum, minimum)
        violation = valid & (distance < self.c.separation)
        self.violation_steps += int(violation.any())
        self.violating_pairs.update(zip(i[violation].tolist(), j[violation].tolist()))
        self.min_history.append(minimum)
        self.k += 1

        arrived = moving & (np.linalg.norm(after - self.goals, axis=1) <= self.c.goal_radius)
        self.arrival[arrived] = self.k * self.c.dt
        self.active[arrived] = False
        self.state[arrived, 2] = 0
        self.history.append(self.state.copy())
        self.active_history.append(self.active.copy())
        self.actions.append(action.copy())
        terminated = not self.active.any()
        truncated = not terminated and self.k >= round(self.c.duration / self.c.dt)
        return self.observe(), terminated, truncated

    def metrics(self):
        reached = np.isfinite(self.arrival)
        # Straight-line travel at nominal cruise speed to the goal disk: a reference,
        # not a physical minimum-time bound. Arrival timing is quantized by dt.
        reference = np.maximum(self.initial_distance - self.c.goal_radius, 0) / self.c.cruise_speed
        excess = self.arrival[reached] - reference[reached]
        return {"seed": self.seed, "agents": self.c.n, "delay_s": self.c.delay_s,
                "simulated_s": self.k * self.c.dt, "arrival_rate": float(reached.mean()),
                "episode_violation": bool(self.violating_pairs),
                "violating_pairs": len(self.violating_pairs),
                "violation_step_fraction": self.violation_steps / max(self.k, 1),
                "minimum_separation_m": self.minimum if np.isfinite(self.minimum) else None,
                "mean_arrival_s": float(self.arrival[reached].mean()) if reached.any() else None,
                "mean_excess_time_vs_cruise_s": float(excess.mean()) if reached.any() else None,
                "mean_path_length_m": float(self.path_length.mean())}

def predict_neighbors(observation, config, horizon_steps=15):
    """Predict neighbors with constant world-frame velocity."""
    
    own_position = observation["own"][:, :2]       # (n, 2)
    relative = observation["neighbor_relative_position"]  # (n, n, 2)
    velocity = observation["neighbor_velocity"]    # (n, n, 2)
    age = observation["observation_age_s"]

    # relative[i, j] = old_position[j] - current_position[i]
    # Recover the old absolute position seen by each observer.
    old_position = own_position[:, None, :] + relative

    # Prediction times: dt, 2*dt, ..., horizon_steps*dt
    future_times = np.arange(1, horizon_steps + 1) * config.dt

    # Advance from the old observation time to each future time.
    predicted = (
        old_position[:, :, None, :]
        + velocity[:, :, None, :]
        * (age + future_times)[None, None, :, None]
    )

    # A currently inactive observer does not need predictions.
    mask = (
        observation["neighbor_mask"]
        & observation["active"][:, None]
    )

    return predicted, mask
def goal_policy(observation, config):
    """Nominal goal tracker. Deliberately ignores neighbors; no safety claim."""
    own = observation["own"]
    delta = observation["goal"] - own[:, :2]
    desired = np.arctan2(delta[:, 1], delta[:, 0])
    return np.column_stack((1.5 * (config.cruise_speed - own[:, 2]),
                            1.8 * wrap(desired - own[:, 3])))

def rollout_ego(state, controls, config):
    """Return positions including the initial position."""
    s = state.copy()
    positions = [s[:2].copy()]

    for acceleration, turn_rate in controls:
        s[2] = np.clip(
            s[2] + acceleration * config.dt,
            0, config.max_speed
        )
        s[3] = wrap(s[3] + turn_rate * config.dt)

        s[:2] += (
            s[2]
            * np.array([np.cos(s[3]), np.sin(s[3])])
            * config.dt
        )
        positions.append(s[:2].copy())

    return np.array(positions)

@dataclass(frozen=True)
class MPCConfig:
    horizon_s: float = 5.0
    blocks: int = 5
    margin_m: float = 3.0
    maxiter: int = 80
    initialization: str = 'cold'
    state_source: str = 'current'

    def __post_init__(self):
        if self.state_source not in ('current', 'stale', 'compensated'):
            raise ValueError('state_source must be current, stale or compensated')
        if self.initialization not in ('cold', 'warm'):
            raise ValueError('initialization must be cold or warm')
        if not np.isfinite(self.horizon_s) or self.horizon_s <= 0:
            raise ValueError('horizon_s must be finite and positive')
        if not np.isfinite(self.margin_m) or self.margin_m < 0:
            raise ValueError('margin_m must be finite and nonnegative')
        if self.blocks < 1 or self.maxiter < 1:
            raise ValueError('blocks and maxiter must be positive')


def empty_diagnostics():
    return dict(solver_calls=0, solver_failures=0, interventions=0,
                max_slack_m=0.0, slack_steps=0, solver_message='not needed',
                warm_start_calls=0, solver_iterations=0, objective_evaluations=0)


def shifted_blocks(previous, block_index, blocks):
    """Shift by one simulation step, then least-squares project onto blocks.

    Projection changes the plan: it is an initial guess, not a safety backup.
    previous has shape (steps, 2), in normalized control units.
    """
    shifted = np.concatenate((previous[1:], previous[-1:]), axis=0)
    return np.array([shifted[block_index == b].mean(axis=0) for b in range(blocks)])


def mpc_filter(observation, config, nominal, settings=None, inspection=None, memory=None):
    """Joint MPC over the supplied report. Slack permits separation violations.

    The reference command is held constant over the horizon. Each vehicle's
    control has `blocks` constant segments. Only the first command is applied.
    Predicted separation is checked along linear transitions, as in step().
    Predicted vehicles remain present over the horizon (conservative near goals).
    """
    settings = settings or MPCConfig()
    ids = np.flatnonzero(observation['active'])
    action = np.zeros_like(nominal, dtype=float)
    info = empty_diagnostics()
    limits = np.array([config.max_accel, config.max_turn_rate])
    reference = np.clip(nominal[ids], -limits, limits)
    action[ids] = reference
    if len(ids) < 2:
        if memory is not None:
            memory.clear()
        return action, info

    states = observation['own'][ids].copy()
    count = len(ids)
    blocks = settings.blocks
    steps = max(blocks, int(np.ceil(settings.horizon_s / config.dt)))
    block_index = np.minimum(np.arange(steps) * blocks // steps, blocks - 1)
    pi, pj = np.triu_indices(count, 1)
    target = config.separation + settings.margin_m
    scaled_reference = reference / limits
    size = count * blocks * 2

    def controls(z):
        return z[:size].reshape(count, blocks, 2)[:, block_index] * limits

    def distances(z):
        u = controls(z)
        # Heading integration is cumulative; speed clipping must be sequential.
        heading = states[:, 3, None] + np.cumsum(u[:, :, 1] * config.dt, axis=1)
        speed = np.empty((count, steps))
        v = states[:, 2].copy()
        for k in range(steps):
            v = np.clip(v + u[:, k, 0] * config.dt, 0, config.max_speed)
            speed[:, k] = v
        increments = speed[:, :, None] * np.stack(
            (np.cos(heading), np.sin(heading)), axis=-1) * config.dt
        paths = np.concatenate((states[:, None, :2],
            states[:, None, :2] + np.cumsum(increments, axis=1)), axis=1)
        relative = paths[pi] - paths[pj]
        r0 = relative[:, :-1]
        dr = np.diff(relative, axis=1)
        fraction = np.clip(-np.sum(r0 * dr, axis=-1) /
                          np.maximum(np.sum(dr * dr, axis=-1), 1e-12), 0, 1)
        return np.linalg.norm(r0 + fraction[..., None] * dr, axis=-1)

    def objective(z):
        u = z[:size].reshape(count, blocks, 2)
        tracking = np.mean((u - scaled_reference[:, None]) ** 2)
        smooth = np.mean(np.diff(u, axis=1) ** 2) if blocks > 1 else 0.0
        return tracking + 0.1 * smooth + 1000.0 * (z[-1] + z[-1] ** 2)

    def constraint(z):
        return distances(z).ravel() / target - 1.0 + z[-1]

    def snapshot(z):
        u = z[:size].reshape(count, blocks, 2)
        tracking = float(np.mean((u - scaled_reference[:, None]) ** 2))
        smoothing = float(0.1 * np.mean(np.diff(u, axis=1) ** 2)) if blocks > 1 else 0.0
        return dict(predicted_minimum_m=float(distances(z).min()),
                    slack_m=float(target * z[-1]), tracking_cost=tracking,
                    smoothing_cost=smoothing,
                    slack_cost=float(1000 * (z[-1] + z[-1] ** 2)),
                    total_cost=float(objective(z)),
                    minimum_soft_constraint=float(constraint(z).min()))

    z0 = np.r_[np.repeat(scaled_reference[:, None], blocks, axis=1).ravel(), 0.0]
    initial_minimum = distances(z0).min()
    if inspection is not None:
        inspection.update(target_m=target, separation_m=config.separation,
                          nominal_zero_slack=snapshot(z0))
    if initial_minimum >= target:
        if memory is not None:
            memory.clear()  # Nominal command replaces the previously optimized plan.
        if inspection is not None:
            inspection.update(solver_called=False, reason='Nominal plan meets target')
        return action, info
    if settings.initialization == 'warm' and memory:
        guess = z0[:size].reshape(count, blocks, 2)
        reused = False
        for row, vehicle_id in enumerate(ids):
            previous = memory.get(int(vehicle_id))
            if previous is not None and previous.shape == (steps, 2):
                guess[row] = shifted_blocks(previous, block_index, blocks)
                reused = True
        z0[:size] = np.clip(z0[:size], -1.0, 1.0)
        info['warm_start_calls'] = int(reused)
        initial_minimum = distances(z0).min()  # New state, reprojected plan.
    z0[-1] = np.clip(1.0 - initial_minimum / target, 0.0, 1.0)
    if inspection is not None:
        inspection['initial'] = snapshot(z0)
        inspection['initialization_used'] = 'warm' if info['warm_start_calls'] else 'cold'
    result = minimize(objective, z0, method='SLSQP',
                      bounds=[(-1.0, 1.0)] * size + [(0.0, 1.0)],
                      constraints={'type': 'ineq', 'fun': constraint},
                      options={'maxiter': settings.maxiter, 'ftol': 1e-5})
    info['solver_calls'] = 1
    info['solver_iterations'] = int(result.nit)
    info['objective_evaluations'] = int(result.nfev)
    info['solver_message'] = str(result.message)
    accepted = (result.success and np.isfinite(result.x).all()
                and constraint(result.x).min() >= -1e-5)
    if inspection is not None:
        inspection.update(solver_called=True, solver_success=bool(result.success),
                          accepted=bool(accepted), iterations=int(result.nit),
                          objective_evaluations=int(result.nfev),
                          solver_message=str(result.message),
                          final=snapshot(result.x) if np.isfinite(result.x).all() else None,
                          returned_action_source='optimized' if accepted else 'braking fallback')
    if accepted:
        action[ids] = np.clip(controls(result.x)[:, 0], -limits, limits)
        info['max_slack_m'] = float(result.x[-1] * target)
        info['slack_steps'] = int(info['max_slack_m'] > 1e-3)
        if memory is not None:
            memory.clear()
            if settings.initialization == 'warm':
                expanded = controls(result.x) / limits
                memory.update({int(vehicle_id): expanded[row].copy()
                               for row, vehicle_id in enumerate(ids)})
    else:
        if memory is not None:
            memory.clear()  # Rejected plans must not seed the next call.
        # Brake with nominal turn rate. This fallback is NOT guaranteed safe.
        action[ids, 0] = -config.max_accel
        info['solver_failures'] = 1
    info['interventions'] = int(np.count_nonzero(
        np.linalg.norm((action[ids] - reference) / limits, axis=1) > 1e-3))
    return action, info


def compensate_report(report, commands, config):
    """Replay sent commands from the report timestamp, without simulator truth.

    Assumes known dynamics, immediate reliable actuation and fixed known goals.
    Arrival/deactivation is predicted using the same goal-disk rule as the plant.
    observation_age_s remains the age of the underlying measurement.
    """
    age_steps = int(round(report['observation_age_s'] / config.dt))
    if age_steps > len(commands):
        raise ValueError('Missing command history for delay compensation')
    state = report['own'].copy()
    active = report['active'].copy()
    limits = np.array([config.max_accel, config.max_turn_rate])
    for sent in commands[len(commands) - age_steps:]:
        action = np.clip(sent, -limits, limits)
        state[active, 2] = np.clip(state[active, 2] + action[active, 0] * config.dt,
                                   0, config.max_speed)
        state[active, 3] = wrap(state[active, 3] + action[active, 1] * config.dt)
        heading = state[:, 3]
        velocity = state[:, 2, None] * np.column_stack((np.cos(heading), np.sin(heading)))
        state[active, :2] += velocity[active] * config.dt
        arrived = active & (np.linalg.norm(state[:, :2] - report['goal'], axis=1)
                            <= config.goal_radius)
        active[arrived] = False
        state[arrived, 2] = 0
    return {**report, 'own': state, 'active': active}


def control_report(env, mode, commands):
    report = env.controller_observation('stale' if mode == 'compensated' else mode)
    return compensate_report(report, commands, env.c) if mode == 'compensated' else report


def inspect_mpc(config, seed, settings, at_s):
    """Advance with baseline, inspect one filter call, then stop without applying it."""
    if not np.isfinite(at_s) or at_s < 0:
        raise ValueError('inspect-at must be finite and nonnegative')
    env = TrafficEnv(config)
    obs = env.reset(seed)
    commands = []
    for _ in range(int(round(at_s / config.dt))):
        command = goal_policy(obs, config)
        commands.append(command.copy())
        obs, terminated, truncated = env.step(command)
        if terminated or truncated:
            raise ValueError('Episode ended before inspection; choose an earlier inspect-at')
    report = dict(seed=seed, simulated_s=env.k * config.dt,
                  setup='Baseline trajectory; current-state MPC; candidate is not applied',
                  mpc_settings=asdict(settings))
    obs = control_report(env, settings.state_source, commands)
    report['setup'] = 'Baseline trajectory; one MPC call; candidate is not applied'
    report['state_source'] = settings.state_source
    report['observation_age_s'] = obs['observation_age_s']
    start = time.perf_counter()
    action, info = mpc_filter(obs, config, goal_policy(obs, config), settings, report)
    report.update(wall_s=time.perf_counter() - start,
                  returned_first_action=action.tolist(), diagnostics=info)
    return report


def run(config, seed, use_mpc=False, settings=None, progress_every=50):
    settings = settings or MPCConfig()
    memory = {}  # Episode-local; use only on consecutive control calls.
    commands = []  # Sent commands, captured BEFORE simulator masking/clipping.
    env = TrafficEnv(config)
    obs = env.reset(seed)
    env.controller = 'centralized_mpc' if use_mpc else 'goal_policy'
    env.state_source = settings.state_source
    env.diagnostics = []
    totals = empty_diagnostics()
    totals.pop('solver_message')
    start = time.perf_counter()
    while True:
        step_start = time.perf_counter()
        obs = control_report(env, settings.state_source, commands)
        observation_age = obs['observation_age_s']
        nominal = goal_policy(obs, config)
        if use_mpc:
            action, info = mpc_filter(obs, config, nominal, settings, memory=memory)
        else:
            action, info = nominal, empty_diagnostics()
        decision_s = time.perf_counter() - step_start
        commands.append(action.copy())
        obs, terminated, truncated = env.step(action)
        env.diagnostics.append({'step': env.k, 'time_s': env.k * config.dt,
                                'observation_age_s': observation_age,
                                'decision_s': decision_s, **info})
        for key in ('solver_calls', 'solver_failures', 'interventions', 'slack_steps',
                    'warm_start_calls', 'solver_iterations', 'objective_evaluations'):
            totals[key] += info[key]
        totals['max_slack_m'] = max(totals['max_slack_m'], info['max_slack_m'])
        if progress_every and use_mpc and env.k % progress_every == 0:
            print(f'  MPC seed={seed}: t={env.k * config.dt:.1f}s, '
                  f'active={env.active.sum()}, failures={totals["solver_failures"]}, '
                  f'elapsed={time.perf_counter() - start:.1f}s', flush=True)
        if terminated or truncated:
            break
    metrics = env.metrics()
    metrics.update(controller=env.controller,
                   accel_noise_std=config.accel_noise_std,
                   initialization=settings.initialization if use_mpc else 'not applicable',
                   wall_s_without_render=time.perf_counter() - start,
                   state_source=settings.state_source,
                   uses_delayed_neighbors=bool(use_mpc and settings.state_source in ('stale', 'compensated')
                                               and config.delay_s > 0),
                   max_observation_age_s=max(d['observation_age_s'] for d in env.diagnostics),
                   mean_decision_s=float(np.mean([d['decision_s'] for d in env.diagnostics])),
                   max_decision_s=float(max(d['decision_s'] for d in env.diagnostics)),
                   **totals)
    return env, metrics


def render(env, output, gif=False):
    """Save an overview and optionally a replay; never rerun the controller."""
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    from matplotlib.animation import FuncAnimation, PillowWriter
    from matplotlib.patches import Circle

    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    h = np.asarray(env.history)
    active = np.asarray(env.active_history)
    fig, (ax, mx) = plt.subplots(1, 2, figsize=(11, 4.8))
    colors = plt.get_cmap('tab10')(np.arange(env.c.n) % 10)
    for i in range(env.c.n):
        ax.plot(h[:, i, 0], h[:, i, 1], color=colors[i], alpha=.4)
        ax.scatter(*env.goals[i], color=colors[i], marker='x', s=55)
    extent = max(np.abs(h[:, :, :2]).max(), np.abs(env.goals).max()) + env.c.separation
    ax.set(xlim=(-extent, extent), ylim=(-extent, extent),
           xlabel='x [m]', ylabel='y [m]', aspect='equal')
    ax.grid(alpha=.2)
    dots = ax.scatter(h[0, :, 0], h[0, :, 1], c=colors, s=45)
    rings = []
    for i in range(env.c.n):
        ring = Circle(h[0, i, :2], env.c.separation / 2,
                      fill=False, color=colors[i], alpha=.5)
        ax.add_patch(ring)
        rings.append(ring)
    times = np.arange(1, len(env.min_history) + 1) * env.c.dt
    mx.plot(times, env.min_history, label='Minimum separation within step')
    mx.axhline(env.c.separation, color='red', ls='--', label='Required separation')
    mx.set(xlabel='Time [s]', ylabel='Distance [m]')
    mx.grid(alpha=.2)
    mx.legend(fontsize=8)
    cursor = mx.axvline(0, color='black', alpha=.3)
    title = ax.set_title('Initial positions and complete paths')
    label = (f'Centralized MPC / {env.state_source} / delay={env.c.delay_s:g}s'
             if env.controller == 'centralized_mpc' else 'Goal tracker / no avoidance')
    fig.suptitle(f'AIRCOORD | {label} | seed {env.seed}')
    fig.tight_layout()
    fig.savefig(output / 'overview.png', dpi=150)
    if gif:
        def update(k):
            points = h[k, :, :2].copy()
            points[~active[k]] = np.nan
            dots.set_offsets(points)
            for i, ring in enumerate(rings):
                ring.center = h[k, i, :2]
                ring.set_visible(bool(active[k, i]))
            title.set_text(f't = {k * env.c.dt:.1f} s')
            cursor.set_xdata([k * env.c.dt] * 2)
            return dots, cursor, title, *rings
        frames = list(range(0, len(h), 3))
        if frames[-1] != len(h) - 1:
            frames.append(len(h) - 1)
        animation = FuncAnimation(fig, update, frames=frames,
                                  interval=3000 * env.c.dt, blit=False)
        # One replay frame per three simulation steps; approximately real time.
        animation.save(output / 'replay.gif', writer=PillowWriter(fps=1 / (3 * env.c.dt)))
    plt.close(fig)


def write_csv(path, rows):
    with Path(path).open('w', newline='', encoding='utf-8') as f:
        writer = csv.DictWriter(f, fieldnames=list(rows[0]))
        writer.writeheader()
        writer.writerows(rows)


def save_episode(env, metrics, output, gif):
    output.mkdir(parents=True, exist_ok=True)
    (output / 'metrics.json').write_text(
        json.dumps(metrics, indent=2, allow_nan=False), encoding='utf-8')
    write_csv(output / 'diagnostics.csv', env.diagnostics)
    np.savez_compressed(output / 'trajectory.npz', state=env.history,
                        accel_disturbance=env.accel_disturbance[:env.k],
                        active=env.active_history, goals=env.goals,
                        action=env.actions, min_separation=env.min_history)
    render(env, output, gif)


def compare_starts(config, settings, first_seed, episodes, output, progress_every=50):
    """Paired closed-loop runs; sequential timing, alternating execution order."""
    output = Path(output)
    output.mkdir(parents=True, exist_ok=True)
    rows, paired = [], []
    for offset, seed in enumerate(range(first_seed, first_seed + episodes)):
        pair = {}
        order = ('cold', 'warm') if offset % 2 == 0 else ('warm', 'cold')
        for mode in order:
            cfg = MPCConfig(**{**asdict(settings), 'initialization': mode})
            print(f'Comparison {offset + 1}/{episodes}: seed={seed}, {mode}', flush=True)
            env, metrics = run(config, seed, True, cfg, progress_every)
            pair[mode] = metrics
            decisions = np.array([d['decision_s'] for d in env.diagnostics])
            metrics['decision_deadline_miss_fraction'] = float(np.mean(decisions > config.dt))
            save_episode(env, metrics, output / mode / f'seed_{seed}', False)
            rows.append(metrics)
            write_csv(output / 'runs.csv', rows)
        cold, warm = pair['cold'], pair['warm']
        paired.append(dict(seed=seed,
            cold_violation=cold['episode_violation'], warm_violation=warm['episode_violation'],
            cold_minimum_m=cold['minimum_separation_m'], warm_minimum_m=warm['minimum_separation_m'],
            cold_wall_s=cold['wall_s_without_render'], warm_wall_s=warm['wall_s_without_render'],
            speedup=cold['wall_s_without_render'] / warm['wall_s_without_render'],
            cold_arrival_rate=cold['arrival_rate'], warm_arrival_rate=warm['arrival_rate']))
        write_csv(output / 'paired.csv', paired)
        summary = dict(config=asdict(config), mpc_settings=asdict(settings),
                       completed_pairs=len(paired), requested_pairs=episodes,
                       seeds=[r['seed'] for r in paired],
                       note=f'Central report: {settings.state_source}; crossing for n=4; seed changes position jitter. '
                            'Closed-loop paths differ. Timing includes all controller decisions; '
                            'simulation waits for the solver.', by_initialization={})
        for mode in ('cold', 'warm'):
            group = [r for r in rows if r['initialization'] == mode]
            summary['by_initialization'][mode] = dict(
                episodes=len(group), violations=sum(r['episode_violation'] for r in group),
                mean_arrival_rate=float(np.mean([r['arrival_rate'] for r in group])),
                worst_minimum_m=min(r['minimum_separation_m'] for r in group
                                    if r['minimum_separation_m'] is not None),
                total_wall_s=sum(r['wall_s_without_render'] for r in group),
                solver_failures=sum(r['solver_failures'] for r in group),
                mean_deadline_miss_fraction=float(np.mean([
                    r['decision_deadline_miss_fraction'] for r in group])))
        (output / 'comparison_summary.json').write_text(
            json.dumps(summary, indent=2, allow_nan=False), encoding='utf-8')
        print(json.dumps(paired[-1], allow_nan=False), flush=True)
    print(json.dumps(summary, indent=2, allow_nan=False), flush=True)
    return summary


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--agents', type=int, default=4)
    p.add_argument('--seed', type=int, default=7)
    p.add_argument('--delay', type=float, default=0.0)
    p.add_argument('--accel-noise-std', type=float, default=0.0,
                   help='Plant-only iid acceleration disturbance std [m/s^2] per dt')
    p.add_argument('--episodes', type=int, default=1)
    p.add_argument('--duration', type=float, default=60.0)
    p.add_argument('--controller', choices=['both', 'baseline', 'mpc'], default='both')
    p.add_argument('--horizon', type=float, default=5.0)
    p.add_argument('--blocks', type=int, default=5)
    p.add_argument('--margin', type=float, default=3.0)
    p.add_argument('--maxiter', type=int, default=80)
    p.add_argument('--initialization', choices=['cold', 'warm'], default='cold')
    p.add_argument('--state-source', choices=['current', 'stale', 'compensated'], default='current',
                   help='Central report: current, stale, or command-replay compensated')
    p.add_argument('--progress-every', type=int, default=50)
    p.add_argument('--gif', action='store_true')
    p.add_argument('--inspect-mpc', action='store_true', help='Inspect one MPC call and exit')
    p.add_argument('--compare-starts', action='store_true', help='Run paired cold/warm MPC for each seed')
    p.add_argument('--inspect-at', type=float, default=10.0, help='Baseline time before inspection [s]')
    p.add_argument('--out', type=Path, default=Path('results'))
    args = p.parse_args()
    if args.episodes < 1 or args.progress_every < 0:
        p.error('episodes must be positive; progress-every must be nonnegative')
    if args.inspect_mpc and args.compare_starts:
        p.error('choose inspect-mpc or compare-starts, not both')
    try:
        config = Config(n=args.agents, delay_s=args.delay, duration=args.duration,
                        accel_noise_std=args.accel_noise_std)
        settings = MPCConfig(args.horizon, args.blocks, args.margin, args.maxiter,
                             args.initialization, args.state_source)
    except ValueError as exc:
        p.error(str(exc))
    args.out.mkdir(parents=True, exist_ok=True)
    if args.compare_starts:
        compare_starts(config, settings, args.seed, args.episodes, args.out, args.progress_every)
        return
    if args.inspect_mpc:
        try:
            report = inspect_mpc(config, args.seed, settings, args.inspect_at)
        except ValueError as exc:
            p.error(str(exc))
        payload = json.dumps(report, indent=2, allow_nan=False)
        (args.out / 'mpc_inspection.json').write_text(payload, encoding='utf-8')
        print(payload, flush=True)
        return
    modes = [False, True] if args.controller == 'both' else [args.controller == 'mpc']
    print(f'Central report: {settings.state_source}; configured delay={config.delay_s:g}s. '
          'Separation is measured from simulator truth.', flush=True)
    rows = []
    for seed in range(args.seed, args.seed + args.episodes):
        for use_mpc in modes:
            name = 'centralized_mpc' if use_mpc else 'goal_policy'
            print(f'Starting {name}, seed={seed}', flush=True)
            env, metrics = run(config, seed, use_mpc, settings, args.progress_every)
            print(json.dumps(metrics, indent=2, allow_nan=False), flush=True)
            run_output = args.out / name / settings.state_source / f'delay_{config.delay_s:g}'
            if use_mpc:
                run_output = run_output / settings.initialization
            save_episode(env, metrics, run_output / f'seed_{seed}', args.gif)
            rows.append(metrics)
            # Save completed runs immediately, even if a later run is interrupted.
            write_csv(args.out / 'comparison.csv', rows)
            summary = {'config': asdict(config), 'mpc_settings': asdict(settings),
                       'observation_note': f'Central report: {settings.state_source}; all dynamic '
                                           'report fields share a timestamp. Metrics use truth.',
                       'episodes': rows, 'by_controller': {}}
            for controller in dict.fromkeys(r['controller'] for r in rows):
                group = [r for r in rows if r['controller'] == controller]
                summary['by_controller'][controller] = {
                    'episodes': len(group),
                    'episode_violation_rate': float(np.mean([r['episode_violation'] for r in group])),
                    'mean_arrival_rate': float(np.mean([r['arrival_rate'] for r in group]))}
            (args.out / 'summary.json').write_text(
                json.dumps(summary, indent=2, allow_nan=False), encoding='utf-8')
    print(f'Saved {len(rows)} runs to {args.out.resolve()}', flush=True)


if __name__ == '__main__':
    main()
